### PR TITLE
sddm: Use wayland as default

### PR DESCRIPTION
**Pull request by ptr1337**
This makes sddm use wayland as default.
The main benefits are, that the Refresh Rate is set to the highest one available, also it appears using Plasma 6.2 beta results into a broken sddm.

The main issue comes, that people with:
- 390xx
- 470xx

Drivers will have issue's using that. We should might put a wiki entry for these cases.

### CODE REVIEW

**Comment by ptr1337** [comment]
We should also add to the Wiki for the "KDE Configuration" following:
https://wiki.archlinux.org/title/SDDM#Match_Plasma_display_configuration

**Comment by TheWyn** [comment]
Last time I attempted this with nvidia-open 560 I got a black screen instead of sddm, I didn't apply session plasma settings to sddm though.  Will try again.

**Review by 1Naim — APPROVED** [review]
I've been using this since day 1, no issues!

This also helps dual GPU systems since Xorg server will run on the dGPU and prevent it from suspending.

**Comment by TheWyn** [comment]
For reference the cause was cachyos sddm themes requiring layer-shell-qt5

**Pull request merged**
